version: '3.8'
services:
  app:
    build:
      context: ./server
      target: dev
    ports:
      - '7000:7000'
    environment:
    - CORS_ALLOWED_ORIGIN=http://localhost:3000
    - DOCS_URL=/docs
    - REDOC_URL=/redoc
    - OPENAPI_URL=/openapi.json
    - DB_HOST=http://dynamodb:8081
    - TABLE_NAME=Blogs
    - AWS_ACCESS_KEY_ID=xxxx
    - AWS_SECRET_ACCESS_KEY=xxxx
    restart: always
    tty: true
    volumes:
      - ./server:/opt/server/:delegated
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -port 8081 -dbPath /ddb-data
    environment:
    - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - $PWD/ddb-data:/ddb-data
    ports:
      - 8081:8081
  dynamod-admin:
    image: instructure/dynamo-local-admin
    environment:
    - DYNAMO_ENDPOINT=http://dynamodb:8081
    - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
      - 8000:8000
