version: '3.8'
services:
  app:
    build:
      context: ./server
      target: dev
    ports:
      - '7000:7000'
    restart: always
    tty: true
    volumes:
      - ./server:/opt/server/:delegated