Resources:
  CognitoUserIdPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: blog-id-pool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ProviderName:
            Fn::GetAtt: ["CognitoUserPool", "ProviderName"]
          ClientId:
            Ref: CognitoUserPoolClient

  CognitoUserIdPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoUserIdPool
      Roles:
        # 認証済みユーザに付与するロール
        authenticated:
          Fn::GetAtt: [AuthenticatedRole, Arn]

  AuthenticatedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cognito-identity:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "execute-api:Invoke"
            Resource:
              # "arn:aws:execute-api:us-east-1:account-id:api-id/*/GET/pets"
              - Fn::Join:
                - ""
                - - "arn:aws:execute-api:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":"
                  - Ref: ApiGatewayRestApi
                  - "/*/POST/"
                  - "${self:provider.apiName}"
  
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: AuthenticatedRole
      AssumeRolePolicyDocument: # このロールに関連付ける信頼ポリシー
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud":
                  Ref: CognitoUserIdPool
              ForAnyValue:StringLike:
                "Cognito-identity.amazonaws.com:amr": authenticated
      ManagedPolicyArns:
      - Ref: AuthenticatedPolicy