Resources:
  BlogBackendRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /blog/backend/
      RoleName: BlogBackendRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
      - PolicyName: BlogBackendPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - '*'
            Resource:
            - 'Fn::Join':
              - ':'
              -
                - 'arn:aws:dynamodb'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'table/${self:custom.envFile.TABLE_NAME}/index/*'
          - Effect: Allow
            Action:
              - dynamodb:CreateTable
              - dynamodb:DescribeTable
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Resource:
            - 'Fn::Join':
              - ':'
              -
                - 'arn:aws:dynamodb'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'table/${self:custom.envFile.TABLE_NAME}'
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - 'Fn::Join':
              - ':'
              -
                - 'arn:aws:logs'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'log-group:/aws/lambda/*:*:*'